### ISSUE TITLE
Players falling through ground when standing up

### ISSUE THREAD

**Issue by SpraxDev** [Sprax2013/BetterChairs#112]
* **Server Version**: 1.17.1
* **Plugin Version**: Probably `v1.3.0`

**Describe the bug**
Reported on Discord, forgotten and by now the reporing user has left the server
https://discord.com/channels/344982818863972352/718492339693289532/878344043619291187
> 小龍
> I find a bug about betterchair.
> In 1.17.1, player sits on a half block or a stair and when he stand up, he falls down if there is nothing under the half block or the stair.
> I can only do is to stop using sit function at this moment.
> 
> Sprax
> I suspect it's a bug in the new version released a couple of days ago?
> 
> 小龍
> Yes

**To Reproduce**
*Unknown*

**Screenshots, Videos, Logs or Errors**
*Unknown*

**Additional context**
*Unknown*

**Comment by SpraxDev** [comment]
This seems to be fixed now - Maybe somebody else reports a similar issue in the future 🤷🏻‍♂️

**Comment by vincentchu37** [comment]
Hi, I'm still experiencing this with the teleport player to old location set to false. Attached are two videos

BetterChairs-v1.5.6.jar on Paper version git-Paper-386 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 4da844f)

```
# Should a player be teleported to its original position when leaving a chair
    TeleportPlayerToOldLocation: false
``` 

https://user-images.githubusercontent.com/19421154/216196338-43025aa4-b850-4cc4-95fd-f819359a701b.mp4


https://user-images.githubusercontent.com/19421154/216196029-211b40b0-9a7f-4436-a2c6-de2b7db0d968.mp4

**Comment by SpraxDev** [comment]
I think I've fixed the issue and it will be part of the next release @vincentchu37.
I'll be closing this issue as resolved but if you still encounter the bug after updating, please let me know!
