### ISSUE TITLE
PlaceholderAPI Placeholders

### ISSUE THREAD

**Issue by DrkMatr1984** [Sprax2013/BetterChairs#114]
**Is your feature request related to a problem? Please describe.**

No problem

**Describe the solution you'd like**

PlaceholderAPI placeholders for whether the player is currently sitting and whether player has their sitting toggled on or off

**Additional context**

Love that you continued this!

**Comment by SpraxDev** [comment]
I am not familiar with PlaceholderAPI but if I understand it correctly, BetterChairs would add new placeholders for other plugins to use, right? Or is it meant to support placeholders in the messages BetterChair sends?

**Comment by DrkMatr1984** [comment]
I mean, technically it can do both, but I just meant for it to provide placeholders for other plugins to retrieve data from, like strings basically. It's pretty simple to do and I could probably put in a PR myself. I'm personally only going to use them for DeluxeMenus. I can create an options menu with it that will be able to toggle sitting off and on in a gui. Retrieving their currently toggled state will allow me to provide custom buttons for on and off.

**Comment by DrkMatr1984** [comment]
https://github.com/SpraxDev/BetterChairs/pull/115
![chairs](https://user-images.githubusercontent.com/5105448/143836690-9d0e19a7-af67-4134-a683-970fbb82e0ba.gif)

**Comment by SpraxDev** [comment]
I've already replied to your PR but for the sake of completion:

I've added PlaceholderAPI support with two placeholders: `sitting` and `chairs_enabled`

I took inspiration from your PR as it helped me understand the PlaceholderAPI a bit easier that with their Wiki alone.
