### ISSUE TITLE
Change jar file to have version number

### ISSUE THREAD

**Issue by makcuber** [Sprax2013/BetterChairs#118]
This is a really minor request, but if you could change the jar file to the have version number in the file name I think that would be helpful for server admins to easily keep track when moving files around on the server. Its not at all an issue to just rename the jar file after you download it, but itd be nice to have it already in the downloaded file name and its pretty common to do so for other plugins. Great plugin in general, thanks for all the work to make it possible!

**Comment by SpraxDev** [comment]
Sure thing, the next update contains the version in the file name ^^

Hopefully I don't forget it and remove it from the name again (in that case, don't hesitate to call me out on that 😄)
