### ISSUE TITLE
(Question) Is BetterChairs faster in terms of performance?

### ISSUE THREAD

**Issue by f1refa11** [Sprax2013/BetterChairs#162]
I want to add BetterChairs because it only has a /sit command that i need, but i have a question: is it faster than GSit plugin that has more features? Although there is no visible difference in performance between these plugins, I still want to choose the fastest one

**Comment by SpraxDev** [comment]
I do not have any experience with GSit as I've never used it.
But I can tell you that I'm pretty confident that BetterChairs (Remastered) does not impact your performance.

If you only want the sit-Command and not any of the right-click stairs features,
you can disable them in the config.

I didn't know that there are people out there only interested in the command, but I can improve performance even more for those people. But the impact compared to the existing code is probably not noticeable even with a hundred players or so :smile:

**Comment by f1refa11** [comment]
Thank you!
