### ISSUE TITLE
Custom Chair blocks 

### ISSUE THREAD

**Issue by Aequotis** [Sprax2013/BetterChairs#171]
**Is your feature request related to a problem? Please describe.**
Plugin has an option for setting custom blocks as chairs. I am trying to set coral fans as chairs but I'm unable to add them to the enabled blocks list regardless of whatever format I try. :( 

**Describe the solution you'd like**
Adding coral as a chair! Specifically bubble coral fan.

**Additional context**
We have a resourcepack which changes coral fans into chair models. Would be very fun to use them as chairs.
- bubble_coral_fan [not waterlogged]
- dead_bubble_coral_wall_fan [not waterlogged]
- dead_brain_coral_fan [not waterlogged]

![image](https://user-images.githubusercontent.com/42449924/213552958-9f36b712-5062-4d67-bca7-d98819e36346.png)

**Comment by SpraxDev** [comment]
Thanks for your report! I was able to confirm the bug and the whole custom block type feature apparently couldn't work in general.

I've fixed the bug and release an update shortly.

---

btw. that screenshot looks very interesting 😄
