### ISSUE TITLE
Chair already occupied message even when seat is free

### ISSUE THREAD

**Issue by vincentchu37** [Sprax2013/BetterChairs#180]
BetterChairs-v1.6.0.jar on Paper version git-Paper-458 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 5100822)

Pretty low priority, as you can just turn off the messages.

If `AllowSwitchingSeats:` and `AlreadyOccupied:` are both set to true. The already occupied message will show even when the "seat" is empty. Trying to switch seats to one the player already occupies pops the message twice. 

I'll update the ticket when I test this with other players :)

Video.

https://user-images.githubusercontent.com/19421154/226197852-063d588c-3808-4584-a581-bc43208c391a.mp4

**Comment by SpraxDev** [comment]
Well that looks weird 😄

**Comment by SpraxDev** [comment]
Thanks for your report again! Honestly, I forgot about this 😅 

I think I fixed it in the release I published today - Would you be able test and see if it is fixed now?

**Comment by vincentchu37** [comment]
All good brother, I also forgot, everything looks good to me! Thanks for your work!
